name: Build Jaspiler
concurrency:
  group: build_jaspiler_${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"
      - "**.rst"
      - "docs/**"
  push:
    paths-ignore:
      - "**.md"
      - "**.rst"
      - "docs/**"

env:
  JASPILER_VERSION: 0.1.0

jobs:
  build_jaspiler_linux_and_windows:
    name: Build Jaspiler for Linux and Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1

      - name: Build the Artifact
        run: gradle build test

      - name: Upload the Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jaspiler-${{ env.JASPILER_VERSION }}
          path: build/libs/*.jar
